stages:
  - build
  - test

build-job:
  stage: build
  image: ubuntu:22.04
  before_script:
    sudo bash startup-script.sh
  script:
    sudo docker build -t yohrannes/coodesh-challenge .
teste-imagem-docker:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Code coverage is 90%"


