stages:
  - build
  - test

build-job:
  stage: build
  image: docker:27.1.2-dind
  script:
    sudo docker build -t yohrannes/coodesh-challenge .
teste-imagem-docker:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Code coverage is 90%"


