stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    ./startup-script.sh
unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... "
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
