stages:
  - build
  - test

build-job:
  stage: build
  image: ubuntu:22.04
  script:
    apt-get update;
    apt-get install -y sudo;
    ls;
teste-imagem-docker:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Code coverage is 90%"


