stages:
  - deploy
  - test
  - build
  #- deploy

install-nginx-test:
  stage: test
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y sudo
    #- whoami
    #- which sudo
    - chmod +x /usr/bin/sudo
    - sudo echo "sudo funcionando..."
    - apt-get install -y systemd libpam-systemd
    #- which systemctl
    - echo "systemd instalado"
  script:
    - sudo bash startup-files/startup-script.sh install-nginx
    - |
      if [ $? -eq 0 ]; then
        echo "NGINX OK"
      else
        echo "Falha na instalação do NGINX"
        exit 1
      fi

check-image-security:
  stage: test
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y sudo
    - whoami
    - which sudo
    - chmod +x /usr/bin/sudo
    - sudo echo "sudo funcionando..."
    - apt-get install -y systemd libpam-systemd
    - which systemctl
    - echo "systemd instalado"
    - sudo apt-get install -y wget apt-transport-https gnupg lsb-release
    - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    - echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
    - sudo apt-get update
    - sudo apt-get install -y trivy
  script:
    - trivy image yohrannes/website-portifolio > trivy-scan.txt
    - |
      if [ $? -eq 0 ]; then
        echo "CHECANDO VULNERABILIDADES DA IMAGEM"
        cat trivy-scan.txt
      else
        echo "Falha na instalação do NGINX"
        exit 1
      fi

build-app-image-test:
  stage: build
  image: docker:27.1.2
  services:
    - docker:27.1.2-dind
  script:
    - docker build -t yohrannes/coodesh-challenge:latest .
    - |
      if [ $? -eq 0 ]; then
        echo "IMAGEM DOCKER OK"
      else
        echo "Falha na instalação do NGINX"
        exit 1
      fi

deploy-with-terraform:
  stage: deploy
  image: docker:23.0.2
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - mkdir -p /root/.config/gcloud
    - echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64" | base64 -d > /root/.config/gcloud/application_default_credentials.json

    - echo "Configuring Terraform backend..."
    - |
      cat <<EOF >> main.tf
      terraform {
        backend "gcs" {
          bucket  = "coodesh-bucket"
          prefix  = "terraform/state"
        }
      }
      EOF

    - echo "Running Terraform init..."
    - docker run -it -v $PWD:/root -w /root hashicorp/terraform:light init

    - echo "Running Terraform plan..."
    - docker run -it -v $PWD:/root -w /root hashicorp/terraform:light plan

