stages:
  - build
  - test

build-job:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16
  script:
    docker build -t yohrannes/coodesh-challenge .
teste-imagem-docker:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Code coverage is 90%"


