stages:
  - build

build-job:
  stage: build
  image: ubuntu:22.04
  script:
    apt-get update;
    apt-get install -y sudo;
    whoami;
    which sudo;
    chmod +x /usr/bin/sudo;
    sudo echo "Sudo funcionando...";
    apt-get install systemd libpam-systemd systemd-ui;
    which systemctl;
    #sudo bash startup-script.sh;