stages:
  - test

build-job:
  stage: test
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y sudo
    - whoami
    - which sudo
    - chmod +x /usr/bin/sudo
    - sudo echo "sudo funcionando..."
    - apt-get install -y systemd libpam-systemd
    - which systemctl
    - echo "systemd instalado"
  script:
    - sudo bash startup-files/startup-script.sh install-nginx
    - |
      if [ $? -eq 0 ]; then
        echo "NGINX OK"
      else
        echo "Falha na instalação do NGINX"
        exit 1
      fi
